---
- name: playbook_update_and_upgrade_ubuntu.
  hosts: localhost

  tasks:
    - name: Ping hosts in the group
      ping:
####
# setup ssh

####
# install packages
    - name: Install packages
      include_tasks: Roles/install-packages.yaml

####
# install brew
    - name: Install brew
      include_tasks: Roles/install_brew.yaml

# homebrew tap repo
    - name: Tap a Homebrew repository, state present
      community.general.homebrew_tap:
        name: "{{ homebrew_taps }}"
        state: present

# install brew packages
    - name: Install brew packages
      include_tasks: Roles/install_brew_packages.yaml   
####
# make folder directory

    - name: Create base folder directory
      ansible.builtin.file:
        path: ~/workspace
        state: directory
        mode: '0755'      
####
# get git directories

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.folder }}"
        update: false
      loop: "{{ git_repo }}"

####
# setup source virtualization

    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: Restart your shell to make changes active