---
- name: Playbook_update_and_upgrade_ubuntu.
  hosts: localhost

  tasks:
    - name: Ping hosts in the group
      ansible.builtin.ping:

    - name: Setup ssh
      ansible.builtin.include_tasks: tasks/setup_ssh.yaml

    - name: Setup git
      ansible.builtin.include_tasks: tasks/setup_git.yaml

    - name: Install packages
      ansible.builtin.include_tasks: tasks/install-packages.yaml

    - name: Install brew
      ansible.builtin.include_tasks: tasks/install_brew.yaml

    - name: Install brew packages
      ansible.builtin.include_tasks: tasks/install_brew_packages.yaml

    - name: Setup k9s plugins when using flux
      ansible.builtin.include_tasks: tasks/setup_k9s.yaml

# setup source virtualization
    - name: Ensure Homebrew shellenv is configured in .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ lookup('env', 'USER') }}/.zshrc"
        line: "alias k='kubectl'"
        insertafter: EOF
