---
- name: playbook_update_and_upgrade_ubuntu.
  hosts: localhost

  tasks:
    - name: Ping hosts in the group
      ping:
####
# setup ssh

####
# install bashrc

####
# install packages

####
# install brew
    - name: Install brew
      include_tasks: Roles/install_brew.yaml

# homebrew tap repo
    - name: Tap a Homebrew repository, state present
      community.general.homebrew_tap:
        name: "{{ homebrew_taps }}"
        state: present

# install brew packages
    - name: Install brew packages
      include_tasks: Roles/install_brew_packages.yaml   
####
# make folder directory

####
# get git directories

####
# setup source virtualization