---
- name: playbook_update_and_upgrade_ubuntu.
  hosts: localhost

  tasks:
    - name: Ping hosts in the group
      ping:

    - name: Setup ssh
      ansible.builtin.include_tasks: tasks/setup_ssh.yaml

    - name: Setup git
      ansible.builtin.include_tasks: tasks/setup_ssh.yaml

    - name: Install packages
      ansible.builtin.include_tasks: tasks/install-packages.yaml

    - name: Install brew
      ansible.builtin.include_tasks: tasks/install_brew.yaml

    - name: Install brew packages
      include_tasks: tasks/install_brew_packages.yaml   

# setup source virtualization
    - name: Ensure Homebrew shellenv is configured in .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ lookup('env', 'USER') }}/.zshrc"
        line: "alias k='kubectl'"
        insertafter: EOF

