---

- name: Check if the k9s folder exist
  ansible.builtin.stat:
    path: ~/.config/k9s
  register: k9s_folder_status

- name: Fail playbook when required folder is missing
  ansible.builtin.fail:
    msg: The k9s folder does not exists
  when: not k9s_folder_status.stat.exists

- name: template plugins.yaml for k9s
  ansible.builtin.template:
    src: "k9s/plugins_{{ gitops_extention }}.yaml"
    dest: ~/.config/k9s/plugins.yaml
