---

install_homebrew_if_missing: true
upgrade_homebrew_packages: false

homebrew_taps:
  - hashicorp/tap
  - fluxcd/tap

brew_packages:
  - hashicorp/tap/terraform
  - kustomize
  - kubie
  - helm
  - k9s
  - kubectl
  - fluxcd/tap/flux

apt_packages:
  - wget